import type { Metadata } from "next";
import 'tailwindcss/tailwind.css';
import "./globals.css";

import { montserrat, santana, acumin, lato, raleway } from "./components/fonts/fonts";

export const metadata: Metadata = {
  title: "Ontegra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body suppressHydrationWarning={true} className={`${santana.variable} ${lato.variable} ${acumin.variable} ${montserrat.variable} ${raleway.variable} font-santana`}>{children}</body>

    </html>
  );
}
